### PR TITLE
adding an attribution to the footer

### PR DESCRIPTION
**Pull request by gbinal**

### CODE REVIEW

**Comment by afeld** [comment]
Kudos @tranhelen and team!

/cc https://github.com/18F/open-source-policy/issues/37

**Comment by seanherron** [comment]
What about "Site design based on http://shopify.github.io"? Might be a bit more accurate since we forked + modified.

**Comment by gbinal** [comment]
works for me.  barring any complaints, I'll make that as a direct commit.

**Comment by afeld** [comment]
:+1:

**Pull request merged**
